#Constantes que representan las opciones del menu
INGRESAR_NUEVO_PRODUCTO = '1'
MOSTRAR_PRODUCTOS_POR_TERMINAL = '2'
BUSCAR_PRODUCTO_POR_NOMBRE = '3'
ELIMINAR_PRODUCTO_POR_INDICE = '4'
FINALIZAR_PROGRAMA = '5'